language: php

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./lib/

before_script:
  - composer install --dev --prefer-source

before_install:
  - composer self-update
